"use client";
import React, { useEffect, useState } from 'react';
import { useAuth } from '../../context/AuthContext';

export default function CustomerPurchases() {
  const { token, user, logout } = useAuth();
  const [orders, setOrders] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchOrders();
  }, [token]);

  const fetchOrders = async () => {
    if (!token) return;
    try {
      const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
      const res = await fetch(`${API_URL}/api/orders/myorders`, {
        headers: { 'Authorization': `Bearer ${token}` }
      });
      if (res.status === 401 || res.status === 403) return logout();
      const data = await res.json();
      setOrders(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleReturn = async (orderId) => {
    if (!window.confirm("Are you sure you want to request a return for this entire order?")) return;
    
    try {
      const API_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:5000';
      const res = await fetch(`${API_URL}/api/orders/${orderId}/return`, {
        method: 'PUT',
        headers: { 'Authorization': `Bearer ${token}` }
      });
      
      if (!res.ok) {
        const errorData = await res.json();
        throw new Error(errorData.message || "Failed to process return");
      }
      
      alert("Return successful. A refund has been issued to your original payment method.");
      await fetchOrders();
    } catch (err) {
      alert(err.message);
    }
  };

  if (loading) return <div className="loading-state">Loading your digital receipts...</div>;

  return (
    <div className="animate-stagger">
      <div className="header-flex">
        <div>
          <h2>My Purchases</h2>
          <p style={{color: 'var(--color-muted)'}}>Review your generated invoices and request returns.</p>
        </div>
      </div>

      {orders.length === 0 ? (
        <div className="glass-panel" style={{padding: '5rem', textAlign: 'center'}}>
          <h3 style={{color: 'var(--color-muted)'}}>No purchases history found</h3>
          <p style={{marginTop: '0.5rem', color: '#a3a3a3'}}>Your orders generated by the administration will appear here.</p>
        </div>
      ) : (
        <div className="orders-grid">
          {orders.map(order => (
            <div key={order.id} className="glass-panel order-card">
              <div className="order-header">
                <div>
                  <h4 style={{fontSize: '1.2rem'}}>Order #{order.id}</h4>
                  <p style={{fontSize: '0.85rem', color: 'var(--color-muted)', marginTop: '0.2rem'}}>
                    {new Date(order.created_at).toLocaleDateString()} at {new Date(order.created_at).toLocaleTimeString()}
                  </p>
                </div>
                <div style={{textAlign: 'right'}}>
                  <h3 className="currency" style={{color: 'var(--color-primary)'}}>₹{Number(order.total_amount).toFixed(2)}</h3>
                  <span className={`badge ${order.status === 'returned' ? 'badge-danger' : order.status === 'completed' ? 'badge-success' : 'badge-warning'}`} style={{marginTop: '0.5rem'}}>
                    {order.status}
                  </span>
                </div>
              </div>
              
              <div className="order-footer">
                {(order.status === 'completed' || order.status === 'pending') ? (
                  <button onClick={() => handleReturn(order.id)} className="btn-secondary" style={{width: '100%'}}>
                    Return Goods
                  </button>
                ) : (
                  <button className="btn-secondary" style={{width: '100%', opacity: 0.5, cursor: 'not-allowed'}} disabled>
                    Return Processed
                  </button>
                )}
              </div>
            </div>
          ))}
        </div>
      )}

      <style jsx>{`
        .header-flex { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 2.5rem; }
        .orders-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(350px, 1fr)); gap: 1.5rem; }
        .order-card { display: flex; flex-direction: column; padding: 0; }
        .order-header { padding: 1.5rem; display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 1px solid rgba(0,0,0,0.05); }
        .order-footer { padding: 1.5rem; background: rgba(255,255,255,0.4); }
        .loading-state { text-align: center; font-weight: 500; color: var(--color-muted); padding: 5rem 0; }
      `}</style>
    </div>
  );
}
